.PHONY: clean All

All:
	@echo "----------Building project:[ challenge16 - Debug ]----------"
	@cd "challenge16" && "$(MAKE)" -f  "challenge16.mk"
clean:
	@echo "----------Cleaning project:[ challenge16 - Debug ]----------"
	@cd "challenge16" && "$(MAKE)" -f  "challenge16.mk" clean
