.PHONY: clean All

All:
	@echo "----------Building project:[ firstProject - Debug ]----------"
	@cd "firstProject" && "$(MAKE)" -f  "firstProject.mk"
clean:
	@echo "----------Cleaning project:[ firstProject - Debug ]----------"
	@cd "firstProject" && "$(MAKE)" -f  "firstProject.mk" clean
