.PHONY: clean All

All:
	@echo "----------Building project:[ challenge2 - Debug ]----------"
	@cd "challenge2" && "$(MAKE)" -f  "challenge2.mk"
clean:
	@echo "----------Cleaning project:[ challenge2 - Debug ]----------"
	@cd "challenge2" && "$(MAKE)" -f  "challenge2.mk" clean
