.PHONY: clean All

All:
	@echo "----------Building project:[ GenericMacros - Debug ]----------"
	@cd "GenericMacros" && "$(MAKE)" -f  "GenericMacros.mk"
clean:
	@echo "----------Cleaning project:[ GenericMacros - Debug ]----------"
	@cd "GenericMacros" && "$(MAKE)" -f  "GenericMacros.mk" clean
