.PHONY: clean All

All:
	@echo "----------Building project:[ Iterator - Debug ]----------"
	@cd "Iterator" && "$(MAKE)" -f  "Iterator.mk"
clean:
	@echo "----------Cleaning project:[ Iterator - Debug ]----------"
	@cd "Iterator" && "$(MAKE)" -f  "Iterator.mk" clean
